name: usa-holidays
version: 0.1.0.0
github: 'kkweon/usa-holidays'
license: BSD3
author: 'Kyung Mo Kweon'
maintainer: 'kkweon@gmail.com'
copyright: '2019 Kyung Mo Kweon'

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kkweon/usa-holidays#readme>

dependencies:
  - base >= 4.7 && < 5
  - time

library:
  source-dirs: src

tests:
  usa-holidays-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - usa-holidays
      - hspec
  usa-holidays-dodctest:
    main: doctest-driver.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - usa-holidays
      - doctest
      - doctest-discover
